// Code generated by ent, DO NOT EDIT.

package image

const (
	// Label holds the string label denoting the image type in the database.
	Label = "image"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldAlt holds the string denoting the alt field in the database.
	FieldAlt = "alt"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldUploadDate holds the string denoting the uploaddate field in the database.
	FieldUploadDate = "upload_date"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// EdgeArticle holds the string denoting the article edge name in mutations.
	EdgeArticle = "article"
	// Table holds the table name of the image in the database.
	Table = "images"
	// ArticleTable is the table that holds the article relation/edge.
	ArticleTable = "images"
	// ArticleInverseTable is the table name for the Article entity.
	// It exists in this package in order to avoid circular dependency with the "article" package.
	ArticleInverseTable = "articles"
	// ArticleColumn is the table column denoting the article relation/edge.
	ArticleColumn = "article_images"
)

// Columns holds all SQL columns for image fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldAlt,
	FieldURL,
	FieldUploadDate,
	FieldOrder,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "images"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"article_images",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
