// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArticlesColumns holds the columns for the "articles" table.
	ArticlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "title", Type: field.TypeString, Size: 32},
		{Name: "short", Type: field.TypeString, Size: 128},
		{Name: "content", Type: field.TypeString},
		{Name: "upload_date", Type: field.TypeTime},
	}
	// ArticlesTable holds the schema information for the "articles" table.
	ArticlesTable = &schema.Table{
		Name:       "articles",
		Columns:    ArticlesColumns,
		PrimaryKey: []*schema.Column{ArticlesColumns[0]},
	}
	// ArticleTitleGuidsColumns holds the columns for the "article_title_guids" table.
	ArticleTitleGuidsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "title_normalized", Type: field.TypeString, Unique: true},
		{Name: "article_title_normalized", Type: field.TypeUUID, Unique: true},
	}
	// ArticleTitleGuidsTable holds the schema information for the "article_title_guids" table.
	ArticleTitleGuidsTable = &schema.Table{
		Name:       "article_title_guids",
		Columns:    ArticleTitleGuidsColumns,
		PrimaryKey: []*schema.Column{ArticleTitleGuidsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "article_title_guids_articles_titleNormalized",
				Columns:    []*schema.Column{ArticleTitleGuidsColumns[2]},
				RefColumns: []*schema.Column{ArticlesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// BlobsColumns holds the columns for the "blobs" table.
	BlobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "blob", Type: field.TypeBytes, SchemaType: map[string]string{"mysql": "mediumblob"}},
		{Name: "content_type", Type: field.TypeString},
	}
	// BlobsTable holds the schema information for the "blobs" table.
	BlobsTable = &schema.Table{
		Name:       "blobs",
		Columns:    BlobsColumns,
		PrimaryKey: []*schema.Column{BlobsColumns[0]},
	}
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "alt", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "upload_date", Type: field.TypeTime},
		{Name: "order", Type: field.TypeInt},
		{Name: "article_images", Type: field.TypeUUID, Nullable: true},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "images_articles_images",
				Columns:    []*schema.Column{ImagesColumns[6]},
				RefColumns: []*schema.Column{ArticlesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "role_users", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_roles_users",
				Columns:    []*schema.Column{UsersColumns[3]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArticlesTable,
		ArticleTitleGuidsTable,
		BlobsTable,
		ImagesTable,
		RolesTable,
		UsersTable,
	}
)

func init() {
	ArticleTitleGuidsTable.ForeignKeys[0].RefTable = ArticlesTable
	ImagesTable.ForeignKeys[0].RefTable = ArticlesTable
	UsersTable.ForeignKeys[0].RefTable = RolesTable
}
