// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kzmijak/zswod_api_go/ent/gallery"
	"github.com/kzmijak/zswod_api_go/ent/image"
	"github.com/kzmijak/zswod_api_go/ent/predicate"
)

// ImageUpdate is the builder for updating Image entities.
type ImageUpdate struct {
	config
	hooks    []Hook
	mutation *ImageMutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (iu *ImageUpdate) Where(ps ...predicate.Image) *ImageUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetAlt sets the "alt" field.
func (iu *ImageUpdate) SetAlt(s string) *ImageUpdate {
	iu.mutation.SetAlt(s)
	return iu
}

// SetNillableAlt sets the "alt" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableAlt(s *string) *ImageUpdate {
	if s != nil {
		iu.SetAlt(*s)
	}
	return iu
}

// ClearAlt clears the value of the "alt" field.
func (iu *ImageUpdate) ClearAlt() *ImageUpdate {
	iu.mutation.ClearAlt()
	return iu
}

// SetOrder sets the "Order" field.
func (iu *ImageUpdate) SetOrder(i int) *ImageUpdate {
	iu.mutation.ResetOrder()
	iu.mutation.SetOrder(i)
	return iu
}

// SetNillableOrder sets the "Order" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableOrder(i *int) *ImageUpdate {
	if i != nil {
		iu.SetOrder(*i)
	}
	return iu
}

// AddOrder adds i to the "Order" field.
func (iu *ImageUpdate) AddOrder(i int) *ImageUpdate {
	iu.mutation.AddOrder(i)
	return iu
}

// ClearOrder clears the value of the "Order" field.
func (iu *ImageUpdate) ClearOrder() *ImageUpdate {
	iu.mutation.ClearOrder()
	return iu
}

// SetGalleryID sets the "gallery" edge to the Gallery entity by ID.
func (iu *ImageUpdate) SetGalleryID(id uuid.UUID) *ImageUpdate {
	iu.mutation.SetGalleryID(id)
	return iu
}

// SetNillableGalleryID sets the "gallery" edge to the Gallery entity by ID if the given value is not nil.
func (iu *ImageUpdate) SetNillableGalleryID(id *uuid.UUID) *ImageUpdate {
	if id != nil {
		iu = iu.SetGalleryID(*id)
	}
	return iu
}

// SetGallery sets the "gallery" edge to the Gallery entity.
func (iu *ImageUpdate) SetGallery(g *Gallery) *ImageUpdate {
	return iu.SetGalleryID(g.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (iu *ImageUpdate) Mutation() *ImageMutation {
	return iu.mutation
}

// ClearGallery clears the "gallery" edge to the Gallery entity.
func (iu *ImageUpdate) ClearGallery() *ImageUpdate {
	iu.mutation.ClearGallery()
	return iu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *ImageUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(iu.hooks) == 0 {
		if err = iu.check(); err != nil {
			return 0, err
		}
		affected, err = iu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ImageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = iu.check(); err != nil {
				return 0, err
			}
			iu.mutation = mutation
			affected, err = iu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iu.hooks) - 1; i >= 0; i-- {
			if iu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (iu *ImageUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *ImageUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *ImageUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *ImageUpdate) check() error {
	if v, ok := iu.mutation.Order(); ok {
		if err := image.OrderValidator(v); err != nil {
			return &ValidationError{Name: "Order", err: fmt.Errorf(`ent: validator failed for field "Image.Order": %w`, err)}
		}
	}
	return nil
}

func (iu *ImageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   image.Table,
			Columns: image.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: image.FieldID,
			},
		},
	}
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.Alt(); ok {
		_spec.SetField(image.FieldAlt, field.TypeString, value)
	}
	if iu.mutation.AltCleared() {
		_spec.ClearField(image.FieldAlt, field.TypeString)
	}
	if value, ok := iu.mutation.Order(); ok {
		_spec.SetField(image.FieldOrder, field.TypeInt, value)
	}
	if value, ok := iu.mutation.AddedOrder(); ok {
		_spec.AddField(image.FieldOrder, field.TypeInt, value)
	}
	if iu.mutation.OrderCleared() {
		_spec.ClearField(image.FieldOrder, field.TypeInt)
	}
	if iu.mutation.GalleryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GalleryTable,
			Columns: []string{image.GalleryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: gallery.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.GalleryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GalleryTable,
			Columns: []string{image.GalleryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: gallery.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ImageUpdateOne is the builder for updating a single Image entity.
type ImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageMutation
}

// SetAlt sets the "alt" field.
func (iuo *ImageUpdateOne) SetAlt(s string) *ImageUpdateOne {
	iuo.mutation.SetAlt(s)
	return iuo
}

// SetNillableAlt sets the "alt" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableAlt(s *string) *ImageUpdateOne {
	if s != nil {
		iuo.SetAlt(*s)
	}
	return iuo
}

// ClearAlt clears the value of the "alt" field.
func (iuo *ImageUpdateOne) ClearAlt() *ImageUpdateOne {
	iuo.mutation.ClearAlt()
	return iuo
}

// SetOrder sets the "Order" field.
func (iuo *ImageUpdateOne) SetOrder(i int) *ImageUpdateOne {
	iuo.mutation.ResetOrder()
	iuo.mutation.SetOrder(i)
	return iuo
}

// SetNillableOrder sets the "Order" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableOrder(i *int) *ImageUpdateOne {
	if i != nil {
		iuo.SetOrder(*i)
	}
	return iuo
}

// AddOrder adds i to the "Order" field.
func (iuo *ImageUpdateOne) AddOrder(i int) *ImageUpdateOne {
	iuo.mutation.AddOrder(i)
	return iuo
}

// ClearOrder clears the value of the "Order" field.
func (iuo *ImageUpdateOne) ClearOrder() *ImageUpdateOne {
	iuo.mutation.ClearOrder()
	return iuo
}

// SetGalleryID sets the "gallery" edge to the Gallery entity by ID.
func (iuo *ImageUpdateOne) SetGalleryID(id uuid.UUID) *ImageUpdateOne {
	iuo.mutation.SetGalleryID(id)
	return iuo
}

// SetNillableGalleryID sets the "gallery" edge to the Gallery entity by ID if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableGalleryID(id *uuid.UUID) *ImageUpdateOne {
	if id != nil {
		iuo = iuo.SetGalleryID(*id)
	}
	return iuo
}

// SetGallery sets the "gallery" edge to the Gallery entity.
func (iuo *ImageUpdateOne) SetGallery(g *Gallery) *ImageUpdateOne {
	return iuo.SetGalleryID(g.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (iuo *ImageUpdateOne) Mutation() *ImageMutation {
	return iuo.mutation
}

// ClearGallery clears the "gallery" edge to the Gallery entity.
func (iuo *ImageUpdateOne) ClearGallery() *ImageUpdateOne {
	iuo.mutation.ClearGallery()
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *ImageUpdateOne) Select(field string, fields ...string) *ImageUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Image entity.
func (iuo *ImageUpdateOne) Save(ctx context.Context) (*Image, error) {
	var (
		err  error
		node *Image
	)
	if len(iuo.hooks) == 0 {
		if err = iuo.check(); err != nil {
			return nil, err
		}
		node, err = iuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ImageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = iuo.check(); err != nil {
				return nil, err
			}
			iuo.mutation = mutation
			node, err = iuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(iuo.hooks) - 1; i >= 0; i-- {
			if iuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, iuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Image)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ImageMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *ImageUpdateOne) SaveX(ctx context.Context) *Image {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *ImageUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *ImageUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *ImageUpdateOne) check() error {
	if v, ok := iuo.mutation.Order(); ok {
		if err := image.OrderValidator(v); err != nil {
			return &ValidationError{Name: "Order", err: fmt.Errorf(`ent: validator failed for field "Image.Order": %w`, err)}
		}
	}
	return nil
}

func (iuo *ImageUpdateOne) sqlSave(ctx context.Context) (_node *Image, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   image.Table,
			Columns: image.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: image.FieldID,
			},
		},
	}
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Image.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, image.FieldID)
		for _, f := range fields {
			if !image.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != image.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.Alt(); ok {
		_spec.SetField(image.FieldAlt, field.TypeString, value)
	}
	if iuo.mutation.AltCleared() {
		_spec.ClearField(image.FieldAlt, field.TypeString)
	}
	if value, ok := iuo.mutation.Order(); ok {
		_spec.SetField(image.FieldOrder, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.AddedOrder(); ok {
		_spec.AddField(image.FieldOrder, field.TypeInt, value)
	}
	if iuo.mutation.OrderCleared() {
		_spec.ClearField(image.FieldOrder, field.TypeInt)
	}
	if iuo.mutation.GalleryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GalleryTable,
			Columns: []string{image.GalleryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: gallery.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.GalleryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GalleryTable,
			Columns: []string{image.GalleryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: gallery.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Image{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
