// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kzmijak/zswod_api_go/ent/predicate"
	"github.com/kzmijak/zswod_api_go/ent/resetpasswordtoken"
	"github.com/kzmijak/zswod_api_go/ent/user"
)

// ResetPasswordTokenQuery is the builder for querying ResetPasswordToken entities.
type ResetPasswordTokenQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ResetPasswordToken
	withOwner  *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResetPasswordTokenQuery builder.
func (rptq *ResetPasswordTokenQuery) Where(ps ...predicate.ResetPasswordToken) *ResetPasswordTokenQuery {
	rptq.predicates = append(rptq.predicates, ps...)
	return rptq
}

// Limit adds a limit step to the query.
func (rptq *ResetPasswordTokenQuery) Limit(limit int) *ResetPasswordTokenQuery {
	rptq.limit = &limit
	return rptq
}

// Offset adds an offset step to the query.
func (rptq *ResetPasswordTokenQuery) Offset(offset int) *ResetPasswordTokenQuery {
	rptq.offset = &offset
	return rptq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rptq *ResetPasswordTokenQuery) Unique(unique bool) *ResetPasswordTokenQuery {
	rptq.unique = &unique
	return rptq
}

// Order adds an order step to the query.
func (rptq *ResetPasswordTokenQuery) Order(o ...OrderFunc) *ResetPasswordTokenQuery {
	rptq.order = append(rptq.order, o...)
	return rptq
}

// QueryOwner chains the current query on the "owner" edge.
func (rptq *ResetPasswordTokenQuery) QueryOwner() *UserQuery {
	query := &UserQuery{config: rptq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rptq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resetpasswordtoken.Table, resetpasswordtoken.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, resetpasswordtoken.OwnerTable, resetpasswordtoken.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(rptq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ResetPasswordToken entity from the query.
// Returns a *NotFoundError when no ResetPasswordToken was found.
func (rptq *ResetPasswordTokenQuery) First(ctx context.Context) (*ResetPasswordToken, error) {
	nodes, err := rptq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{resetpasswordtoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rptq *ResetPasswordTokenQuery) FirstX(ctx context.Context) *ResetPasswordToken {
	node, err := rptq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ResetPasswordToken ID from the query.
// Returns a *NotFoundError when no ResetPasswordToken ID was found.
func (rptq *ResetPasswordTokenQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rptq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{resetpasswordtoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rptq *ResetPasswordTokenQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rptq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ResetPasswordToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ResetPasswordToken entity is found.
// Returns a *NotFoundError when no ResetPasswordToken entities are found.
func (rptq *ResetPasswordTokenQuery) Only(ctx context.Context) (*ResetPasswordToken, error) {
	nodes, err := rptq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{resetpasswordtoken.Label}
	default:
		return nil, &NotSingularError{resetpasswordtoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rptq *ResetPasswordTokenQuery) OnlyX(ctx context.Context) *ResetPasswordToken {
	node, err := rptq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ResetPasswordToken ID in the query.
// Returns a *NotSingularError when more than one ResetPasswordToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (rptq *ResetPasswordTokenQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rptq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{resetpasswordtoken.Label}
	default:
		err = &NotSingularError{resetpasswordtoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rptq *ResetPasswordTokenQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rptq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ResetPasswordTokens.
func (rptq *ResetPasswordTokenQuery) All(ctx context.Context) ([]*ResetPasswordToken, error) {
	if err := rptq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rptq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rptq *ResetPasswordTokenQuery) AllX(ctx context.Context) []*ResetPasswordToken {
	nodes, err := rptq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ResetPasswordToken IDs.
func (rptq *ResetPasswordTokenQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := rptq.Select(resetpasswordtoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rptq *ResetPasswordTokenQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rptq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rptq *ResetPasswordTokenQuery) Count(ctx context.Context) (int, error) {
	if err := rptq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rptq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rptq *ResetPasswordTokenQuery) CountX(ctx context.Context) int {
	count, err := rptq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rptq *ResetPasswordTokenQuery) Exist(ctx context.Context) (bool, error) {
	if err := rptq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rptq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rptq *ResetPasswordTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := rptq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResetPasswordTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rptq *ResetPasswordTokenQuery) Clone() *ResetPasswordTokenQuery {
	if rptq == nil {
		return nil
	}
	return &ResetPasswordTokenQuery{
		config:     rptq.config,
		limit:      rptq.limit,
		offset:     rptq.offset,
		order:      append([]OrderFunc{}, rptq.order...),
		predicates: append([]predicate.ResetPasswordToken{}, rptq.predicates...),
		withOwner:  rptq.withOwner.Clone(),
		// clone intermediate query.
		sql:    rptq.sql.Clone(),
		path:   rptq.path,
		unique: rptq.unique,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (rptq *ResetPasswordTokenQuery) WithOwner(opts ...func(*UserQuery)) *ResetPasswordTokenQuery {
	query := &UserQuery{config: rptq.config}
	for _, opt := range opts {
		opt(query)
	}
	rptq.withOwner = query
	return rptq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ResetPasswordToken.Query().
//		GroupBy(resetpasswordtoken.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rptq *ResetPasswordTokenQuery) GroupBy(field string, fields ...string) *ResetPasswordTokenGroupBy {
	grbuild := &ResetPasswordTokenGroupBy{config: rptq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rptq.sqlQuery(ctx), nil
	}
	grbuild.label = resetpasswordtoken.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.ResetPasswordToken.Query().
//		Select(resetpasswordtoken.FieldCreateTime).
//		Scan(ctx, &v)
func (rptq *ResetPasswordTokenQuery) Select(fields ...string) *ResetPasswordTokenSelect {
	rptq.fields = append(rptq.fields, fields...)
	selbuild := &ResetPasswordTokenSelect{ResetPasswordTokenQuery: rptq}
	selbuild.label = resetpasswordtoken.Label
	selbuild.flds, selbuild.scan = &rptq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a ResetPasswordTokenSelect configured with the given aggregations.
func (rptq *ResetPasswordTokenQuery) Aggregate(fns ...AggregateFunc) *ResetPasswordTokenSelect {
	return rptq.Select().Aggregate(fns...)
}

func (rptq *ResetPasswordTokenQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rptq.fields {
		if !resetpasswordtoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rptq.path != nil {
		prev, err := rptq.path(ctx)
		if err != nil {
			return err
		}
		rptq.sql = prev
	}
	return nil
}

func (rptq *ResetPasswordTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ResetPasswordToken, error) {
	var (
		nodes       = []*ResetPasswordToken{}
		withFKs     = rptq.withFKs
		_spec       = rptq.querySpec()
		loadedTypes = [1]bool{
			rptq.withOwner != nil,
		}
	)
	if rptq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, resetpasswordtoken.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ResetPasswordToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ResetPasswordToken{config: rptq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rptq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rptq.withOwner; query != nil {
		if err := rptq.loadOwner(ctx, query, nodes, nil,
			func(n *ResetPasswordToken, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rptq *ResetPasswordTokenQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*ResetPasswordToken, init func(*ResetPasswordToken), assign func(*ResetPasswordToken, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ResetPasswordToken)
	for i := range nodes {
		if nodes[i].user_reset_password_token == nil {
			continue
		}
		fk := *nodes[i].user_reset_password_token
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_reset_password_token" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rptq *ResetPasswordTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rptq.querySpec()
	_spec.Node.Columns = rptq.fields
	if len(rptq.fields) > 0 {
		_spec.Unique = rptq.unique != nil && *rptq.unique
	}
	return sqlgraph.CountNodes(ctx, rptq.driver, _spec)
}

func (rptq *ResetPasswordTokenQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := rptq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (rptq *ResetPasswordTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   resetpasswordtoken.Table,
			Columns: resetpasswordtoken.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: resetpasswordtoken.FieldID,
			},
		},
		From:   rptq.sql,
		Unique: true,
	}
	if unique := rptq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rptq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resetpasswordtoken.FieldID)
		for i := range fields {
			if fields[i] != resetpasswordtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rptq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rptq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rptq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rptq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rptq *ResetPasswordTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rptq.driver.Dialect())
	t1 := builder.Table(resetpasswordtoken.Table)
	columns := rptq.fields
	if len(columns) == 0 {
		columns = resetpasswordtoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rptq.sql != nil {
		selector = rptq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rptq.unique != nil && *rptq.unique {
		selector.Distinct()
	}
	for _, p := range rptq.predicates {
		p(selector)
	}
	for _, p := range rptq.order {
		p(selector)
	}
	if offset := rptq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rptq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ResetPasswordTokenGroupBy is the group-by builder for ResetPasswordToken entities.
type ResetPasswordTokenGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rptgb *ResetPasswordTokenGroupBy) Aggregate(fns ...AggregateFunc) *ResetPasswordTokenGroupBy {
	rptgb.fns = append(rptgb.fns, fns...)
	return rptgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rptgb *ResetPasswordTokenGroupBy) Scan(ctx context.Context, v any) error {
	query, err := rptgb.path(ctx)
	if err != nil {
		return err
	}
	rptgb.sql = query
	return rptgb.sqlScan(ctx, v)
}

func (rptgb *ResetPasswordTokenGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range rptgb.fields {
		if !resetpasswordtoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rptgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rptgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rptgb *ResetPasswordTokenGroupBy) sqlQuery() *sql.Selector {
	selector := rptgb.sql.Select()
	aggregation := make([]string, 0, len(rptgb.fns))
	for _, fn := range rptgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rptgb.fields)+len(rptgb.fns))
		for _, f := range rptgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rptgb.fields...)...)
}

// ResetPasswordTokenSelect is the builder for selecting fields of ResetPasswordToken entities.
type ResetPasswordTokenSelect struct {
	*ResetPasswordTokenQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rpts *ResetPasswordTokenSelect) Aggregate(fns ...AggregateFunc) *ResetPasswordTokenSelect {
	rpts.fns = append(rpts.fns, fns...)
	return rpts
}

// Scan applies the selector query and scans the result into the given value.
func (rpts *ResetPasswordTokenSelect) Scan(ctx context.Context, v any) error {
	if err := rpts.prepareQuery(ctx); err != nil {
		return err
	}
	rpts.sql = rpts.ResetPasswordTokenQuery.sqlQuery(ctx)
	return rpts.sqlScan(ctx, v)
}

func (rpts *ResetPasswordTokenSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(rpts.fns))
	for _, fn := range rpts.fns {
		aggregation = append(aggregation, fn(rpts.sql))
	}
	switch n := len(*rpts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		rpts.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		rpts.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := rpts.sql.Query()
	if err := rpts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
