// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kzmijak/zswod_api_go/ent/predicate"
	"github.com/kzmijak/zswod_api_go/ent/resetpasswordtoken"
)

// ResetPasswordTokenDelete is the builder for deleting a ResetPasswordToken entity.
type ResetPasswordTokenDelete struct {
	config
	hooks    []Hook
	mutation *ResetPasswordTokenMutation
}

// Where appends a list predicates to the ResetPasswordTokenDelete builder.
func (rptd *ResetPasswordTokenDelete) Where(ps ...predicate.ResetPasswordToken) *ResetPasswordTokenDelete {
	rptd.mutation.Where(ps...)
	return rptd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rptd *ResetPasswordTokenDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rptd.hooks) == 0 {
		affected, err = rptd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResetPasswordTokenMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rptd.mutation = mutation
			affected, err = rptd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rptd.hooks) - 1; i >= 0; i-- {
			if rptd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rptd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rptd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rptd *ResetPasswordTokenDelete) ExecX(ctx context.Context) int {
	n, err := rptd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rptd *ResetPasswordTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: resetpasswordtoken.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: resetpasswordtoken.FieldID,
			},
		},
	}
	if ps := rptd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rptd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ResetPasswordTokenDeleteOne is the builder for deleting a single ResetPasswordToken entity.
type ResetPasswordTokenDeleteOne struct {
	rptd *ResetPasswordTokenDelete
}

// Exec executes the deletion query.
func (rptdo *ResetPasswordTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := rptdo.rptd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{resetpasswordtoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rptdo *ResetPasswordTokenDeleteOne) ExecX(ctx context.Context) {
	rptdo.rptd.ExecX(ctx)
}
