// Code generated by ent, DO NOT EDIT.

package article

const (
	// Label holds the string label denoting the article type in the database.
	Label = "article"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldArticleGUID holds the string denoting the article_guid field in the database.
	FieldArticleGUID = "article_guid"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldShort holds the string denoting the short field in the database.
	FieldShort = "short"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldUploadDate holds the string denoting the upload_date field in the database.
	FieldUploadDate = "upload_date"
	// FieldTitleNormalized holds the string denoting the title_normalized field in the database.
	FieldTitleNormalized = "title_normalized"
	// EdgeImages holds the string denoting the images edge name in mutations.
	EdgeImages = "images"
	// Table holds the table name of the article in the database.
	Table = "articles"
	// ImagesTable is the table that holds the images relation/edge.
	ImagesTable = "images"
	// ImagesInverseTable is the table name for the Image entity.
	// It exists in this package in order to avoid circular dependency with the "image" package.
	ImagesInverseTable = "images"
	// ImagesColumn is the table column denoting the images relation/edge.
	ImagesColumn = "article_images"
)

// Columns holds all SQL columns for article fields.
var Columns = []string{
	FieldID,
	FieldArticleGUID,
	FieldTitle,
	FieldShort,
	FieldContent,
	FieldUploadDate,
	FieldTitleNormalized,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// ShortValidator is a validator for the "short" field. It is called by the builders before save.
	ShortValidator func(string) error
)
