// Code generated by ent, DO NOT EDIT.

package custompage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/kzmijak/zswod_api_go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// IconId applies equality check predicate on the "iconId" field. It's identical to IconIdEQ.
func IconId(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIconId), v))
	})
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateTime), v))
	})
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateTime), v))
	})
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitle), v))
	})
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldURL), v))
	})
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContent), v))
	})
}

// IsExternal applies equality check predicate on the "isExternal" field. It's identical to IsExternalEQ.
func IsExternal(v bool) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIsExternal), v))
	})
}

// Link applies equality check predicate on the "link" field. It's identical to LinkEQ.
func Link(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLink), v))
	})
}

// Section applies equality check predicate on the "section" field. It's identical to SectionEQ.
func Section(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSection), v))
	})
}

// IconIdEQ applies the EQ predicate on the "iconId" field.
func IconIdEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIconId), v))
	})
}

// IconIdNEQ applies the NEQ predicate on the "iconId" field.
func IconIdNEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIconId), v))
	})
}

// IconIdIn applies the In predicate on the "iconId" field.
func IconIdIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldIconId), v...))
	})
}

// IconIdNotIn applies the NotIn predicate on the "iconId" field.
func IconIdNotIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldIconId), v...))
	})
}

// IconIdGT applies the GT predicate on the "iconId" field.
func IconIdGT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIconId), v))
	})
}

// IconIdGTE applies the GTE predicate on the "iconId" field.
func IconIdGTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIconId), v))
	})
}

// IconIdLT applies the LT predicate on the "iconId" field.
func IconIdLT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIconId), v))
	})
}

// IconIdLTE applies the LTE predicate on the "iconId" field.
func IconIdLTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIconId), v))
	})
}

// IconIdContains applies the Contains predicate on the "iconId" field.
func IconIdContains(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldIconId), v))
	})
}

// IconIdHasPrefix applies the HasPrefix predicate on the "iconId" field.
func IconIdHasPrefix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldIconId), v))
	})
}

// IconIdHasSuffix applies the HasSuffix predicate on the "iconId" field.
func IconIdHasSuffix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldIconId), v))
	})
}

// IconIdIsNil applies the IsNil predicate on the "iconId" field.
func IconIdIsNil() predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldIconId)))
	})
}

// IconIdNotNil applies the NotNil predicate on the "iconId" field.
func IconIdNotNil() predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldIconId)))
	})
}

// IconIdEqualFold applies the EqualFold predicate on the "iconId" field.
func IconIdEqualFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldIconId), v))
	})
}

// IconIdContainsFold applies the ContainsFold predicate on the "iconId" field.
func IconIdContainsFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldIconId), v))
	})
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateTime), v))
	})
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreateTime), v))
	})
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreateTime), v...))
	})
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreateTime), v...))
	})
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreateTime), v))
	})
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreateTime), v))
	})
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreateTime), v))
	})
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreateTime), v))
	})
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdateTime), v...))
	})
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdateTime), v...))
	})
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdateTime), v))
	})
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdateTime), v))
	})
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitle), v))
	})
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTitle), v))
	})
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTitle), v...))
	})
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTitle), v...))
	})
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTitle), v))
	})
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTitle), v))
	})
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTitle), v))
	})
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTitle), v))
	})
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTitle), v))
	})
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTitle), v))
	})
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTitle), v))
	})
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTitle), v))
	})
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTitle), v))
	})
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldURL), v))
	})
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldURL), v))
	})
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldURL), v...))
	})
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldURL), v...))
	})
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldURL), v))
	})
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldURL), v))
	})
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldURL), v))
	})
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldURL), v))
	})
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldURL), v))
	})
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldURL), v))
	})
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldURL), v))
	})
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldURL), v))
	})
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldURL), v))
	})
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContent), v))
	})
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldContent), v))
	})
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldContent), v...))
	})
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldContent), v...))
	})
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldContent), v))
	})
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldContent), v))
	})
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldContent), v))
	})
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldContent), v))
	})
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldContent), v))
	})
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldContent), v))
	})
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldContent), v))
	})
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldContent), v))
	})
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldContent), v))
	})
}

// IsExternalEQ applies the EQ predicate on the "isExternal" field.
func IsExternalEQ(v bool) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIsExternal), v))
	})
}

// IsExternalNEQ applies the NEQ predicate on the "isExternal" field.
func IsExternalNEQ(v bool) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIsExternal), v))
	})
}

// IsExternalIsNil applies the IsNil predicate on the "isExternal" field.
func IsExternalIsNil() predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldIsExternal)))
	})
}

// IsExternalNotNil applies the NotNil predicate on the "isExternal" field.
func IsExternalNotNil() predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldIsExternal)))
	})
}

// LinkEQ applies the EQ predicate on the "link" field.
func LinkEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLink), v))
	})
}

// LinkNEQ applies the NEQ predicate on the "link" field.
func LinkNEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLink), v))
	})
}

// LinkIn applies the In predicate on the "link" field.
func LinkIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldLink), v...))
	})
}

// LinkNotIn applies the NotIn predicate on the "link" field.
func LinkNotIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldLink), v...))
	})
}

// LinkGT applies the GT predicate on the "link" field.
func LinkGT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLink), v))
	})
}

// LinkGTE applies the GTE predicate on the "link" field.
func LinkGTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLink), v))
	})
}

// LinkLT applies the LT predicate on the "link" field.
func LinkLT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLink), v))
	})
}

// LinkLTE applies the LTE predicate on the "link" field.
func LinkLTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLink), v))
	})
}

// LinkContains applies the Contains predicate on the "link" field.
func LinkContains(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldLink), v))
	})
}

// LinkHasPrefix applies the HasPrefix predicate on the "link" field.
func LinkHasPrefix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldLink), v))
	})
}

// LinkHasSuffix applies the HasSuffix predicate on the "link" field.
func LinkHasSuffix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldLink), v))
	})
}

// LinkIsNil applies the IsNil predicate on the "link" field.
func LinkIsNil() predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldLink)))
	})
}

// LinkNotNil applies the NotNil predicate on the "link" field.
func LinkNotNil() predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldLink)))
	})
}

// LinkEqualFold applies the EqualFold predicate on the "link" field.
func LinkEqualFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldLink), v))
	})
}

// LinkContainsFold applies the ContainsFold predicate on the "link" field.
func LinkContainsFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldLink), v))
	})
}

// SectionEQ applies the EQ predicate on the "section" field.
func SectionEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSection), v))
	})
}

// SectionNEQ applies the NEQ predicate on the "section" field.
func SectionNEQ(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSection), v))
	})
}

// SectionIn applies the In predicate on the "section" field.
func SectionIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSection), v...))
	})
}

// SectionNotIn applies the NotIn predicate on the "section" field.
func SectionNotIn(vs ...string) predicate.CustomPage {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSection), v...))
	})
}

// SectionGT applies the GT predicate on the "section" field.
func SectionGT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSection), v))
	})
}

// SectionGTE applies the GTE predicate on the "section" field.
func SectionGTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSection), v))
	})
}

// SectionLT applies the LT predicate on the "section" field.
func SectionLT(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSection), v))
	})
}

// SectionLTE applies the LTE predicate on the "section" field.
func SectionLTE(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSection), v))
	})
}

// SectionContains applies the Contains predicate on the "section" field.
func SectionContains(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSection), v))
	})
}

// SectionHasPrefix applies the HasPrefix predicate on the "section" field.
func SectionHasPrefix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSection), v))
	})
}

// SectionHasSuffix applies the HasSuffix predicate on the "section" field.
func SectionHasSuffix(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSection), v))
	})
}

// SectionEqualFold applies the EqualFold predicate on the "section" field.
func SectionEqualFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSection), v))
	})
}

// SectionContainsFold applies the ContainsFold predicate on the "section" field.
func SectionContainsFold(v string) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSection), v))
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AttachmentsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.Attachment) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AttachmentsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomPage) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomPage) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomPage) predicate.CustomPage {
	return predicate.CustomPage(func(s *sql.Selector) {
		p(s.Not())
	})
}
