// Code generated by ent, DO NOT EDIT.

package blob

const (
	// Label holds the string label denoting the blob type in the database.
	Label = "blob"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlob holds the string denoting the blob field in the database.
	FieldBlob = "blob"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldContentType holds the string denoting the contenttype field in the database.
	FieldContentType = "content_type"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the blob in the database.
	Table = "blobs"
)

// Columns holds all SQL columns for blob fields.
var Columns = []string{
	FieldID,
	FieldBlob,
	FieldName,
	FieldContentType,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
