// Code generated by ent, DO NOT EDIT.

package blob

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the blob type in the database.
	Label = "blob"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldBlob holds the string denoting the blob field in the database.
	FieldBlob = "blob"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldAlt holds the string denoting the alt field in the database.
	FieldAlt = "alt"
	// FieldContentType holds the string denoting the contenttype field in the database.
	FieldContentType = "content_type"
	// Table holds the table name of the blob in the database.
	Table = "blobs"
)

// Columns holds all SQL columns for blob fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldBlob,
	FieldTitle,
	FieldAlt,
	FieldContentType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
