// Code generated by ent, DO NOT EDIT.

package attachment

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the attachment type in the database.
	Label = "attachment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIconId holds the string denoting the iconid field in the database.
	FieldIconId = "icon_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeBlob holds the string denoting the blob edge name in mutations.
	EdgeBlob = "blob"
	// EdgePage holds the string denoting the page edge name in mutations.
	EdgePage = "page"
	// EdgeArticle holds the string denoting the article edge name in mutations.
	EdgeArticle = "article"
	// Table holds the table name of the attachment in the database.
	Table = "attachments"
	// BlobTable is the table that holds the blob relation/edge.
	BlobTable = "attachments"
	// BlobInverseTable is the table name for the Blob entity.
	// It exists in this package in order to avoid circular dependency with the "blob" package.
	BlobInverseTable = "blobs"
	// BlobColumn is the table column denoting the blob relation/edge.
	BlobColumn = "blob_attachments"
	// PageTable is the table that holds the page relation/edge.
	PageTable = "attachments"
	// PageInverseTable is the table name for the CustomPage entity.
	// It exists in this package in order to avoid circular dependency with the "custompage" package.
	PageInverseTable = "custom_pages"
	// PageColumn is the table column denoting the page relation/edge.
	PageColumn = "custom_page_attachments"
	// ArticleTable is the table that holds the article relation/edge.
	ArticleTable = "attachments"
	// ArticleInverseTable is the table name for the Article entity.
	// It exists in this package in order to avoid circular dependency with the "article" package.
	ArticleInverseTable = "articles"
	// ArticleColumn is the table column denoting the article relation/edge.
	ArticleColumn = "article_attachments"
)

// Columns holds all SQL columns for attachment fields.
var Columns = []string{
	FieldID,
	FieldIconId,
	FieldTitle,
	FieldDescription,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "attachments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"article_attachments",
	"blob_attachments",
	"custom_page_attachments",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
